apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: alvs
type: Opaque
stringData:
  POSTGRES_DB: "test_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"  # В production использовать безопасный пароль!
