---
# Переменные для веб-сервера NGINX
nginx_worker_connections: 1024
nginx_listen_port: 80
nginx_listen_address: "0.0.0.0"
nginx_root_dir: "/var/www/html"

# FQDN для сайтов
nginx_site_a_fqdn: "server.example.local"
nginx_site_cname_fqdn: "alias.example.local"

# Имена директорий для сайтов
nginx_site_a_dir: "site_a"
nginx_site_cname_dir: "site_cname"
