all:
  children:
    k8s_cluster:
      children:
        k8s_masters:
          hosts:
            k8s-master:
              ansible_host: 192.168.100.103
              ansible_user: mike_1111
              ansible_ssh_private_key_file: ~/.ssh/id_ed25519
              node_role: master
        
        k8s_workers:
          hosts:
            k8s-worker-1:
              ansible_host: 192.168.100.233
              ansible_user: mike_1111
              ansible_ssh_private_key_file: ~/.ssh/id_ed25519
              node_role: worker
            
            k8s-worker-2:
              ansible_host: 192.168.100.239
              ansible_user: mike_1111
              ansible_ssh_private_key_file: ~/.ssh/id_ed25519
              node_role: worker

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
